print("My Daily Routine")
print("I wake up at 7 AM.")
print("I go to school at 8 AM.")
print("I play with my friends in the evening.")
print("i study for 2 hours in the night.")
print("Total studied hours in a week:", 2 * 7)